[package]
name = "polynomials"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
rand = "0.8"
sha2 = "0.10"
ark-bls12-381 = "0.3"
ark-ff = "0.3"
ark-poly = "0.3"
ark-std = "0.3"

[dev-dependencies]
criterion = "0.3"
